### ISSUE TITLE
Issue while trying to run training loop

### ISSUE THREAD

**Issue by nteslyuk** [huangyebiaoke/steel-pipe-weld-defect-detection#3]
I have a problem reproducing your code while trying to run `train.py` script, this is the error:

```
Traceback (most recent call last):
  File "yolov5/train.py", line 481, in <module>
    opt.data, opt.cfg, opt.hyp = check_file(opt.data), check_file(opt.cfg), check_file(opt.hyp)  # check files
  File "/home/tesnik/Downloads/steel-pipe-weld-defect-detection/yolov5/utils/general.py", line 70, in check_file
    assert len(files), 'File Not Found: %s' % file  # assert file was found
AssertionError: File Not Found: data/coco128.yaml
```

Can you please specify with more details how can I run the training loop?
Thanks.

**Comment by huangyebiaoke** [comment]
File Not Found ERROR: 
Please check that the `coco128.yaml` file is in the correct directory, 
the default directory is `data/coco128.yaml`, you can replace it with `py train.py --data "your custom dir/custom.yaml"`.
The format of yaml file please look at yolov5 official documentation.
